image:
- ubuntu1804

clone_depth: 3

build: off

init:
- sudo apt-get install -yq --no-install-suggests --no-install-recommends libhdf5-dev > /dev/null

install:
- cd build
- cmake ..
- cmake --build .

test_script: ctest --output-on-failure

