language: c
fast_finish: true

os:
  - linux
  - osx
  
env: FC=gfortran

group: travis_latest

git:
  depth: 3

before_install:
  - if [[ $TRAVIS_OS_NAME == osx ]]; then
      brew update;
      brew install gcc || true;
      brew link --overwrite gcc;
      export FC=gfortran;
      brew install hdf5;
    fi

install:
  - cd app
  - cmake ../src
  - make

script:
  - make test
    
on_failure:
  - ctest -V
