language: minimal
group: travis_latest
dist: xenial

git:
  depth: 25
  quiet: true

addons:
  apt:
    sources: ubuntu-toolchain-r-test
    packages:
    - gfortran-6
    - libhdf5-dev

matrix:
  include:
  - os: linux
    env: FC=gfortran-6
  - os: osx
    env: FC=gfortran
    before_install:
    - brew update > /dev/null
    - brew upgrade cmake > /dev/null
    - brew install gcc > /dev/null
    - brew install hdf5 > /dev/null

install:
- cd build
- cmake ..
- cmake --build . --parallel

script: ctest --parallel --output-on-failure
