language: c
group: travis_latest
dist: xenial

git:
  depth: 3
  quiet: true

addons:
  apt:
    sources: ubuntu-toolchain-r-test
    packages:
    - gfortran-6
    - libhdf5-dev

matrix:
  include:
  - os: linux
    env: FC=gfortran-6
  - os: osx
    env: FC=gfortran
    before_install:
    - brew install gcc > /dev/null
    - brew install hdf5 > /dev/null

install:
- cd bin
- cmake ..
- cmake --build .

script: ctest --output-on-failure

