name = "h5fortran"
description = "Lightweight object-oriented HDF5 interface"
categories = "io"
version = "4.6.3"

[build]
external-modules = ["hdf5", "h5lt"]
link = ["hdf5", "hdf5_hl", "hdf5_fortran", "hdf5hl_fortran"]
