name = "h5fortran"
description = "Lightweight object-oriented HDF5 interface"
categories = "io"
version = "4.6.3"

[build]
auto-tests = false
external-modules = ["hdf5", "h5lt"]
link = ["hdf5_hl_fortran", "hdf5_fortran", "hdf5_hl", "hdf5"]

[install]
library = true
