name = "h5fortran"
description = "Lightweight object-oriented HDF5 interface"
categories = "io"
version = "4.10.1"

[build]
auto-tests = false
auto-examples = false
external-modules = ["hdf5", "h5lt"]

[install]
library = true

[[test]]
name = "minimal"
main = "test_minimal.f90"

[[test]]
name = "array"
main = "test_array.f90"

[[test]]
name = "attributes"
main = "test_attributes.f90"

[[test]]
name = "cast"
main = "test_cast.f90"

[[test]]
name = "write"
main = "test_write.f90"

[[test]]
name = "deflate_write"
main = "test_deflate_write.f90"

[[test]]
name = "deflate_read"
main = "test_deflate_read.f90"

[[test]]
name = "deflate_props"
main = "test_deflate_props.f90"

[[test]]
name = "destructor"
main = "test_destructor.f90"

[[test]]
name = "exist"
main = "test_exist.f90"

[[test]]
name = "layout"
main = "test_layout.f90"

[[test]]
name = "lt"
main = "test_lt.f90"

[[test]]
name = "scalar"
main = "test_scalar.f90"

[[test]]
name = "shape"
main = "test_shape.f90"

[[test]]
name = "string"
main = "test_string.f90"

[[test]]
name = "version"
main = "test_version.f90"

[dependencies]
hdf5 = '*'
