name: ci

on:
  push:
    paths:
      - "**/CMakeLists.txt"
      - "**.cmake"
      - "**.f90"
      - ".github/workflows/ci.yml"


jobs:

  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      matrix:
        shared: [true, false]
        gcc: [8, 11]

    env:
      CC: gcc-${{ matrix.gcc }}
      FC: gfortran-${{ matrix.gcc }}

    steps:

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: install h5py
      run: pip install h5py

    - name: install hdf5
      run: |
        sudo apt update
        sudo apt install --no-install-recommends gcc-${{ matrix.gcc }} gfortran-${{ matrix.gcc}} ninja-build libhdf5-dev

    - uses: actions/checkout@v3

    - run: cmake --preset multi -DCMAKE_INSTALL_PREFIX=${{ runner.temp }} -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }}

    - name: Build Debug
      run: cmake --build --parallel --preset debug
    - name: Test Debug
      run: ctest --preset debug --output-junit test-debug.xml

    - name: Build Release
      run: cmake --build --parallel --preset release
    - name: Test Release
      run: ctest --preset release --output-junit test-release.xml

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: build/test-*.xml

    - run: cmake --install build

    - name: configure examples
      run: cmake -S example -B example/build -DCMAKE_PREFIX_PATH:PATH=${{ runner.temp }} -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }}
    - name: build examples
      run: cmake --build example/build --parallel
    - name: Test examples
      run: ctest --test-dir example/build -V


  linux-coverage:
    needs: linux
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: install hdf5
      run: |
        sudo apt update
        sudo apt install --no-install-recommends libhdf5-dev

    - name: install Gcovr
      run: pip install gcovr

    - run: cmake --preset coverage
    - run: cmake --build --parallel --preset coverage

    - name: Code coverage
      run: cmake --build --parallel --preset run-coverage

    - uses: actions/upload-artifact@v3
      with:
        name: coverage-report-html
        path: build-coverage/coverage/


  linux-build:
    needs: linux
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      matrix:
        shared: [true, false]

    steps:

    - uses: actions/checkout@v3

    - name: Configure HDF5
      run: cmake -S scripts -B scripts/build -DCMAKE_INSTALL_PREFIX=${{ runner.temp }} -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }}

    - name: Build/install HDF5
      run: cmake --build scripts/build --parallel

    - name: configure h5fortran
      run: cmake -B build -DCMAKE_INSTALL_PREFIX=${{ runner.temp }} -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }} -DCMAKE_PREFIX_PATH=${{ runner.temp }}

    - name: build h5fortran
      run: cmake --build build --parallel

    - name: test h5fortran
      run: ctest --test-dir build --preset default

    - name: install h5fortran
      run: cmake --install build

    - name: configure examples
      run: cmake -S example -B example/build -DCMAKE_PREFIX_PATH:PATH=${{ runner.temp }} -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }}
    - name: build Examples
      run: cmake --build example/build --parallel
    - name: Test Examples
      run: ctest --test-dir example/build -V
