name: ci
env:
  CMAKE_GENERATOR: Ninja

on:
  push:
    paths:
      - "**/CMakeLists.txt"
      - "**.cmake"
      - "**.f90"
      - ".github/workflows/ci.yml"

jobs:

  linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: install hdf5
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends ninja-build gfortran libhdf5-dev

    - run: cmake -B build -DCMAKE_INSTALL_PREFIX=~/hdf5
    - run: cmake --build build --parallel
    - run: cmake --install build
    - run: ctest --parallel 2 --output-on-failure
      working-directory: build

    - run: cmake -S Examples -B Examples/build -Dh5fortran_ROOT=~/hdf5
    - run: cmake --build Examples/build --parallel
    - run: ctest --parallel 2 --output-on-failure
      working-directory: Examples/build


  mac:
    needs: linux
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - run: brew install hdf5 ninja

    - run: cmake -B build -DCMAKE_INSTALL_PREFIX=~/hdf5
    - run: cmake --build build --parallel
    - run: cmake --install build
    - run: ctest --parallel 2 --output-on-failure
      working-directory: build

    - run: cmake -S Examples -B Examples/build -Dh5fortran_ROOT=~/hdf5
    - run: cmake --build Examples/build --parallel
    - run: ctest --parallel 2 --output-on-failure
      working-directory: Examples/build
