name: ci

on:
  push:
    paths:
      - "**/CMakeLists.txt"
      - "**.cmake"
      - "**.f90"
      - ".github/workflows/ci.yml"

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: install hdf5
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends gfortran libhdf5-dev

    - run: cmake -B build
    - run: cmake --build build --parallel
    - run: ctest --parallel 2 --output-on-failure
      working-directory: build

    - name: build Examples
      run: |
        cmake -B Examples/build -S Examples
        cmake --build Examples/build --parallel

    - name: test examples
      run: ctest --parallel 2 --output-on-failure
      working-directory: Examples/build

  mac:
    needs: linux
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - run: brew install hdf5

    - run: cmake -B build
    - run: cmake --build build --parallel

    - run: ctest --parallel 2 --output-on-failure
      working-directory: build
