name: build

env:
   HOMEBREW_NO_INSTALL_CLEANUP: 1

on:
  push:
    paths:
      - "scripts/CMakeLists.txt"
      - "cmake/libraries.json"
      - ".github/workflows/ci_build.yml"

jobs:

  linux_mac:
    timeout-minutes: 20

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        shared: [true, false]
        exclude:
        - os: macos-latest
          shared: true

    runs-on: ${{ matrix.os}}

    steps:

    - name: install GCC (MacOS)
      if: runner.os == 'macOS'
      run: brew reinstall gcc

    - uses: actions/checkout@v3

    - name: Configure HDF5
      run: cmake -S scripts -B scripts/build -DCMAKE_INSTALL_PREFIX=${{ runner.temp }} -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }}

    - name: Build/install HDF5
      run: cmake --build scripts/build --parallel

    - name: configure h5fortran
      run: cmake -B build -DCMAKE_INSTALL_PREFIX=${{ runner.temp }} -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }} -DCMAKE_PREFIX_PATH=${{ runner.temp }}

    - name: build h5fortran
      run: cmake --build build --parallel

    - name: test h5fortran
      run: ctest --test-dir build --preset default

    - name: install h5fortran
      run: cmake --install build

    - name: configure examples
      run: cmake -S example -B example/build -DCMAKE_PREFIX_PATH:PATH=${{ runner.temp }} -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }}
    - name: build Examples
      run: cmake --build example/build --parallel
    - name: Test Examples
      run: ctest --test-dir example/build -V

# build works but takes a long time, so skip
  # msys2:
  #   timeout-minutes: 30
  #   runs-on: windows-latest
  #   env:
  #     CMAKE_GENERATOR: MinGW Makefiles

  #   strategy:
  #     matrix:
  #       shared: [true, false]

  #   steps:
  #   - uses: msys2/setup-msys2@v2
  #     with:
  #       update: true
  #       install: >-
  #         mingw-w64-x86_64-gcc-fortran

  #   - name: Put MSYS2_MinGW64 on PATH
  #     run: echo "${{ runner.temp }}/msys64/mingw64/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

  #   - uses: actions/checkout@v3

  #   - name: Configure HDF5
  #     run: cmake -S scripts -B scripts/build -DCMAKE_INSTALL_PREFIX=${{ runner.temp }} -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }}

  #   - name: Build/install HDF5
  #     run: cmake --build scripts/build --parallel

  #   - name: configure h5fortran
  #     run: cmake -B build -DCMAKE_INSTALL_PREFIX=${{ runner.temp }} -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }} -DCMAKE_PREFIX_PATH=${{ runner.temp }}

  #   - name: build h5fortran
  #     run: cmake --build build --parallel

  #   - name: test h5fortran
  #     run: ctest --test-dir build --preset default -V

  #   - run: cmake --install build
