name: ci_linux

on:
  push:
    paths:
      - "**/CMakeLists.txt"
      - "**.cmake"
      - "**.f90"
      - ".github/workflows/ci_linux.yml"

jobs:

  default:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: ctest -S setup.cmake -VV
      env:
        FC: gfortran-9
        CC: gcc-9

  examples:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: cmake -B Examples/build -S Examples
    - run: cmake --build Examples/build

    - run: ctest -V
      working-directory: Examples/build
