name: ci_linux

on:
  push:
    paths:
      - "**/CMakeLists.txt"
      - "**.cmake"
      - "**.f90"
      - ".github/workflows/ci_linux.yml"

jobs:

  cmake:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends gfortran libhdf5-dev

    - run: ctest -S setup.cmake -VV
