name: ci_linux

on:
  push:
    paths:
      - "**.build"
      - "**.txt"
      - "**.f90"
      - ".github/workflows/ci_linux.yml"
  pull_request:
    paths:
      - "**.build"
      - "**.txt"
      - "**.f90"
      - ".github/workflows/ci_linux.yml"

jobs:

  linuxMeson:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: pip install -r requirements.txt
    - run: sudo apt install -yq --no-install-recommends gfortran libhdf5-dev
    - run: meson setup build
      env:
        FC: gfortran
    - run: ninja -C build
    - run: meson test -C build -v
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Linux_Meson_Testlog
        path: build/meson-logs/testlog.txt

  linuxCmake:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: sudo apt install -yq --no-install-recommends gfortran libhdf5-dev
    - name: CMake configure
      run: |
        mkdir build
        cd build
        cmake ..
      env:
        FC: gfortran
    - run: cmake --build build --parallel
    - run: ctest -V
      working-directory: build
