name: ci_mac

on:
  push:
    paths:
      - "**.f90"
  pull_request:
    paths:
      - "**.f90"

jobs:

  macMeson:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: python -m pip install meson ninja
    - run: brew install pkg-config gcc hdf5
    - run: meson setup build --default-library=shared
      env:
        FC: gfortran-9
        CC: gcc-9
    - run: meson test -C build -v
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Mac_Meson_Testlog
        path: build/meson-logs/testlog.txt

  macCmake:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install packages
      run: brew install pkg-config gcc hdf5
    - run: cmake -B build
      env:
        FC: gfortran-9
        CC: gcc-9
    - run: cmake --build build --parallel
    - run: ctest -V
      working-directory: build
