name: ci_windows
env:
  CMAKE_GENERATOR: Ninja
  CTEST_PARALLEL_LEVEL: 4
  CMAKE_BUILD_TYPE: Release

on:
  push:
    paths:
      - "**/CMakeLists.txt"
      - "**.cmake"
      - ".github/workflows/ci_windows.yml"
  pull_request:
  release:
    types: [published]


jobs:

  msys2:
    timeout-minutes: 30
    runs-on: windows-latest

    strategy:
      matrix:
        shared: [true, false]

    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-gcc-fortran
          mingw-w64-x86_64-hdf5
    # cmake install needed because of default to msys2 shell

    - uses: actions/checkout@v2

    - run: cmake --preset multi --install-prefix=${HOME} -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }}
    - run: cmake --build --preset debug
    - run: ctest --preset debug -V

    - run: cmake --build --preset release
    - run: ctest --preset release

    - run: cmake --install build

    - name: configure examples
      run: cmake -S Examples -B Examples/build -DCMAKE_PREFIX_PATH:PATH=${HOME} -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }}
    - name: build Examples
      run: cmake --build Examples/build
    - name: Test Examples
      run: ctest --test-dir Examples/build -V


  msys2-build:
    timeout-minutes: 30
    runs-on: windows-latest

    strategy:
      matrix:
        shared: [true, false]

    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-gcc-fortran
    # cmake install needed because of default to msys2 shell

    - uses: actions/checkout@v2

    # static build
    - run: cmake -B build --preset build --install-prefix=${HOME} -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }}
    - run: cmake --build build
    - run: ctest --test-dir build --preset default -V
    - run: cmake --install build
