name: ci_windows

env:
  CTEST_NO_TESTS_ACTION: error
  CTEST_PARALLEL_LEVEL: 4
  CMAKE_BUILD_PARALLEL_LEVEL: 4

on:
  push:
    paths:
      - "**.c"
      - "**.cpp"
      - "**.f90"
      - "**.F90"
      - "**/CMakeLists.txt"
      - "**.cmake"
      - ".github/workflows/ci_windows.yml"
      - "!memcheck.cmake"
      - "!coverage.cmake"


jobs:

  msys2:
    timeout-minutes: 30
    runs-on: windows-latest

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-gcc-fortran
          mingw-w64-x86_64-hdf5

    - name: Put MSYS2_MinGW64 on PATH
      run: echo "${{ runner.temp }}/msys64/mingw64/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - uses: actions/checkout@v4

    - name: config
      run: cmake --preset default -G "MinGW Makefiles" --debug-find-pkg=HDF5 --install-prefix ${{ runner.temp }}

    - name: print config log
      if: ${{ failure() }}
      run: cat build/CMakeFiles/CMakeConfigureLog.yaml

    - name: Build
      run: cmake --build --preset default

    - name: test
      run: ctest --preset default

    - name: install package
      run: cmake --install build

    - name: example workflow
      run: cmake -S example -B example/build -G "MinGW Makefiles" -DCMAKE_PREFIX_PATH=${{ runner.temp }}

    - run: cmake --build example/build

    - run: ctest --test-dir example/build -V
